import { SCHEMA_VERSION } from "./constants.js";
import { daysFromNow } from "../utils/format.js";

export const seedState = () => {
  const now = new Date().toISOString();
  return {
    schemaVersion: SCHEMA_VERSION,
    ui: {
      theme: "light",
      reducedMotion: false,
      searchQuery: "",
    },
    session: {
      currentUserId: "user-admin",
      tenantId: "tenant-demo",
    },
    tenants: [
      {
        id: "tenant-demo",
        name: "Demo School",
        createdAt: now,
        updatedAt: now,
      },
    ],
    users: [
      { id: "user-admin", name: "Agnieszka Admin", role: "admin", tenantId: "tenant-demo", createdAt: now, updatedAt: now },
      { id: "user-teacher-1", name: "Marek Nowak", role: "teacher", tenantId: "tenant-demo", createdAt: now, updatedAt: now },
      { id: "user-teacher-2", name: "Karolina Zielińska", role: "teacher", tenantId: "tenant-demo", createdAt: now, updatedAt: now },
      { id: "user-student-1", name: "Ola Kowalska", role: "student", tenantId: "tenant-demo", createdAt: now, updatedAt: now },
      { id: "user-student-2", name: "Jan Mazur", role: "student", tenantId: "tenant-demo", createdAt: now, updatedAt: now },
      { id: "user-student-3", name: "Zuzia Wójcik", role: "student", tenantId: "tenant-demo", createdAt: now, updatedAt: now },
      { id: "user-student-4", name: "Piotr Lis", role: "student", tenantId: "tenant-demo", createdAt: now, updatedAt: now },
      { id: "user-student-5", name: "Natalia Góra", role: "student", tenantId: "tenant-demo", createdAt: now, updatedAt: now },
      { id: "user-student-6", name: "Kacper Wilk", role: "student", tenantId: "tenant-demo", createdAt: now, updatedAt: now },
    ],
    classes: [
      { id: "class-7a", name: "7A", tenantId: "tenant-demo", createdAt: now, updatedAt: now },
      { id: "class-8b", name: "8B", tenantId: "tenant-demo", createdAt: now, updatedAt: now },
    ],
    groups: [
      { id: "group-math-7a", name: "Matematyka 7A", classId: "class-7a", tenantId: "tenant-demo", createdAt: now, updatedAt: now },
      { id: "group-biology-8b", name: "Biologia 8B", classId: "class-8b", tenantId: "tenant-demo", createdAt: now, updatedAt: now },
      { id: "group-robotics", name: "Robotyka międzyszkolna", classId: null, tenantId: "tenant-demo", createdAt: now, updatedAt: now },
    ],
    relations: {
      memberOf: [
        { userId: "user-student-1", scopeType: "class", scopeId: "class-7a" },
        { userId: "user-student-2", scopeType: "class", scopeId: "class-7a" },
        { userId: "user-student-3", scopeType: "class", scopeId: "class-7a" },
        { userId: "user-student-4", scopeType: "class", scopeId: "class-8b" },
        { userId: "user-student-5", scopeType: "class", scopeId: "class-8b" },
        { userId: "user-student-6", scopeType: "class", scopeId: "class-8b" },
        { userId: "user-student-1", scopeType: "group", scopeId: "group-math-7a" },
        { userId: "user-student-2", scopeType: "group", scopeId: "group-math-7a" },
        { userId: "user-student-3", scopeType: "group", scopeId: "group-math-7a" },
        { userId: "user-student-4", scopeType: "group", scopeId: "group-biology-8b" },
        { userId: "user-student-5", scopeType: "group", scopeId: "group-biology-8b" },
        { userId: "user-student-6", scopeType: "group", scopeId: "group-biology-8b" },
        { userId: "user-student-1", scopeType: "group", scopeId: "group-robotics" },
        { userId: "user-student-4", scopeType: "group", scopeId: "group-robotics" },
      ],
      instructorOf: [
        { userId: "user-teacher-1", scopeType: "class", scopeId: "class-7a" },
        { userId: "user-teacher-2", scopeType: "class", scopeId: "class-8b" },
        { userId: "user-teacher-1", scopeType: "group", scopeId: "group-math-7a" },
        { userId: "user-teacher-2", scopeType: "group", scopeId: "group-biology-8b" },
        { userId: "user-teacher-1", scopeType: "group", scopeId: "group-robotics" },
      ],
    },
    announcements: [
      {
        id: "ann-1",
        title: "Start tygodnia projektowego",
        body: "W tym tygodniu skupiamy się na projektach zespołowych.",
        scopeType: "class",
        scopeId: "class-7a",
        authorId: "user-teacher-1",
        tenantId: "tenant-demo",
        createdAt: daysFromNow(-2),
        updatedAt: daysFromNow(-2),
      },
      {
        id: "ann-2",
        title: "Wycieczka do muzeum",
        body: "Prosimy o zgody do piątku.",
        scopeType: "class",
        scopeId: "class-8b",
        authorId: "user-teacher-2",
        tenantId: "tenant-demo",
        createdAt: daysFromNow(-3),
        updatedAt: daysFromNow(-3),
      },
      {
        id: "ann-3",
        title: "Robotyka - spotkanie online",
        body: "Widzimy się jutro na wideokonferencji.",
        scopeType: "group",
        scopeId: "group-robotics",
        authorId: "user-teacher-1",
        tenantId: "tenant-demo",
        createdAt: daysFromNow(-1),
        updatedAt: daysFromNow(-1),
      },
      {
        id: "ann-4",
        title: "Konsultacje indywidualne",
        body: "W tym tygodniu dostępne dodatkowe godziny konsultacji.",
        scopeType: "class",
        scopeId: "class-7a",
        authorId: "user-teacher-1",
        tenantId: "tenant-demo",
        createdAt: daysFromNow(-6),
        updatedAt: daysFromNow(-6),
      },
    ],
    materials: [
      { id: "mat-1", title: "Ułamki - repetytorium", tag: "math", scopeType: "class", scopeId: "class-7a", authorId: "user-teacher-1", tenantId: "tenant-demo", createdAt: daysFromNow(-1), updatedAt: daysFromNow(-1) },
      { id: "mat-2", title: "Ćwiczenia z biologii", tag: "bio", scopeType: "class", scopeId: "class-8b", authorId: "user-teacher-2", tenantId: "tenant-demo", createdAt: daysFromNow(-2), updatedAt: daysFromNow(-2) },
      { id: "mat-3", title: "Robotyka: plan projektu", tag: "stem", scopeType: "group", scopeId: "group-robotics", authorId: "user-teacher-1", tenantId: "tenant-demo", createdAt: daysFromNow(-3), updatedAt: daysFromNow(-3) },
      { id: "mat-4", title: "Analiza tekstu", tag: "polish", scopeType: "class", scopeId: "class-7a", authorId: "user-teacher-1", tenantId: "tenant-demo", createdAt: daysFromNow(-4), updatedAt: daysFromNow(-4) },
      { id: "mat-5", title: "Laboratorium DNA", tag: "bio", scopeType: "group", scopeId: "group-biology-8b", authorId: "user-teacher-2", tenantId: "tenant-demo", createdAt: daysFromNow(-5), updatedAt: daysFromNow(-5) },
      { id: "mat-6", title: "Matematyka: powtórka", tag: "math", scopeType: "group", scopeId: "group-math-7a", authorId: "user-teacher-1", tenantId: "tenant-demo", createdAt: daysFromNow(-6), updatedAt: daysFromNow(-6) },
      { id: "mat-7", title: "Notatki do historii", tag: "history", scopeType: "class", scopeId: "class-8b", authorId: "user-teacher-2", tenantId: "tenant-demo", createdAt: daysFromNow(-7), updatedAt: daysFromNow(-7) },
      { id: "mat-8", title: "Checklist: projekt zespołowy", tag: "project", scopeType: "group", scopeId: "group-robotics", authorId: "user-teacher-1", tenantId: "tenant-demo", createdAt: daysFromNow(-8), updatedAt: daysFromNow(-8) },
    ],
    assignments: [
      { id: "asg-1", title: "Zadanie: ułamki", description: "Rozwiąż zestaw 1-5", dueDate: daysFromNow(3), scopeType: "class", scopeId: "class-7a", authorId: "user-teacher-1", tenantId: "tenant-demo", createdAt: daysFromNow(-2), updatedAt: daysFromNow(-2) },
      { id: "asg-2", title: "Biologia: raport", description: "Opis doświadczenia", dueDate: daysFromNow(5), scopeType: "class", scopeId: "class-8b", authorId: "user-teacher-2", tenantId: "tenant-demo", createdAt: daysFromNow(-3), updatedAt: daysFromNow(-3) },
      { id: "asg-3", title: "Robotyka: prototyp", description: "Dodaj schemat", dueDate: daysFromNow(2), scopeType: "group", scopeId: "group-robotics", authorId: "user-teacher-1", tenantId: "tenant-demo", createdAt: daysFromNow(-1), updatedAt: daysFromNow(-1) },
      { id: "asg-4", title: "Matematyka: quiz", description: "Odpowiedz na 10 pytań", dueDate: daysFromNow(1), scopeType: "group", scopeId: "group-math-7a", authorId: "user-teacher-1", tenantId: "tenant-demo", createdAt: daysFromNow(-4), updatedAt: daysFromNow(-4) },
      { id: "asg-5", title: "Biologia: mapa pojęć", description: "Stwórz mapę", dueDate: daysFromNow(7), scopeType: "group", scopeId: "group-biology-8b", authorId: "user-teacher-2", tenantId: "tenant-demo", createdAt: daysFromNow(-5), updatedAt: daysFromNow(-5) },
      { id: "asg-6", title: "Historia: prezentacja", description: "Prezentacja 5 slajdów", dueDate: daysFromNow(4), scopeType: "class", scopeId: "class-7a", authorId: "user-teacher-1", tenantId: "tenant-demo", createdAt: daysFromNow(-6), updatedAt: daysFromNow(-6) },
    ],
    submissions: [
      { id: "sub-1", assignmentId: "asg-1", studentId: "user-student-1", content: "Moje rozwiązania", attachment: "plik.pdf", status: "submitted", createdAt: daysFromNow(-1), updatedAt: daysFromNow(-1) },
      { id: "sub-2", assignmentId: "asg-1", studentId: "user-student-2", content: "Rozwiązania 1-5", attachment: "", status: "graded", grade: "5", feedback: "Bardzo dobrze", createdAt: daysFromNow(-1), updatedAt: daysFromNow(-1) },
      { id: "sub-3", assignmentId: "asg-2", studentId: "user-student-4", content: "Raport lab", attachment: "", status: "graded", grade: "4+", feedback: "Dobra struktura", createdAt: daysFromNow(-2), updatedAt: daysFromNow(-2) },
      { id: "sub-4", assignmentId: "asg-3", studentId: "user-student-1", content: "Opis prototypu", attachment: "schemat.png", status: "submitted", createdAt: daysFromNow(-1), updatedAt: daysFromNow(-1) },
      { id: "sub-5", assignmentId: "asg-4", studentId: "user-student-2", content: "Quiz odpowiedzi", attachment: "", status: "graded", grade: "5", feedback: "Komplet", createdAt: daysFromNow(-2), updatedAt: daysFromNow(-2) },
      { id: "sub-6", assignmentId: "asg-5", studentId: "user-student-5", content: "Mapa pojęć", attachment: "", status: "submitted", createdAt: daysFromNow(-1), updatedAt: daysFromNow(-1) },
    ],
    notes: [
      { id: "note-1", title: "Plan nauki", body: "Powtórka do testu", scopeType: "private", scopeId: null, ownerId: "user-student-1", tenantId: "tenant-demo", createdAt: daysFromNow(-1), updatedAt: daysFromNow(-1) },
      { id: "note-2", title: "Definicje", body: "Kluczowe pojęcia", scopeType: "private", scopeId: null, ownerId: "user-student-2", tenantId: "tenant-demo", createdAt: daysFromNow(-2), updatedAt: daysFromNow(-2) },
      { id: "note-3", title: "Strategia projektu", body: "Podział zadań", scopeType: "group", scopeId: "group-robotics", ownerId: "user-teacher-1", tenantId: "tenant-demo", createdAt: daysFromNow(-3), updatedAt: daysFromNow(-3) },
      { id: "note-4", title: "Wspólne notatki", body: "Najważniejsze wzory", scopeType: "class", scopeId: "class-7a", ownerId: "user-teacher-1", tenantId: "tenant-demo", createdAt: daysFromNow(-4), updatedAt: daysFromNow(-4) },
      { id: "note-5", title: "Moje cele", body: "Przygotować prezentację", scopeType: "private", scopeId: null, ownerId: "user-student-4", tenantId: "tenant-demo", createdAt: daysFromNow(-5), updatedAt: daysFromNow(-5) },
      { id: "note-6", title: "Podsumowanie biologii", body: "Reakcje enzymatyczne", scopeType: "class", scopeId: "class-8b", ownerId: "user-teacher-2", tenantId: "tenant-demo", createdAt: daysFromNow(-6), updatedAt: daysFromNow(-6) },
    ],
    chatThreads: [
      { id: "chat-1", name: "7A - ogólny", scopeType: "class", scopeId: "class-7a", tenantId: "tenant-demo", createdAt: now, updatedAt: now },
      { id: "chat-2", name: "8B - ogólny", scopeType: "class", scopeId: "class-8b", tenantId: "tenant-demo", createdAt: now, updatedAt: now },
      { id: "chat-3", name: "Robotyka", scopeType: "group", scopeId: "group-robotics", tenantId: "tenant-demo", createdAt: now, updatedAt: now },
    ],
    chatMessages: Array.from({ length: 20 }).map((_, index) => ({
      id: `msg-${index + 1}`,
      threadId: index < 7 ? "chat-1" : index < 14 ? "chat-2" : "chat-3",
      authorId: index % 2 === 0 ? "user-student-1" : "user-teacher-1",
      body: `Wiadomość ${index + 1}`,
      createdAt: daysFromNow(-1),
      updatedAt: daysFromNow(-1),
    })),
    activityLog: [
      { id: "act-1", type: "create", label: "Dodano ogłoszenie", userId: "user-teacher-1", createdAt: daysFromNow(-1) },
      { id: "act-2", type: "submit", label: "Oddano zadanie", userId: "user-student-2", createdAt: daysFromNow(-2) },
      { id: "act-3", type: "grade", label: "Ocena wystawiona", userId: "user-teacher-2", createdAt: daysFromNow(-3) },
      { id: "act-4", type: "message", label: "Nowa wiadomość", userId: "user-student-1", createdAt: daysFromNow(-1) },
    ],
  };
};
