export const CONFIG = {
  storageKey: "outlandGearCart",
  storageVersion: 1,
  currency: "PLN",
  perPage: 8,
  debounceMs: 200,
  selectors: {
    searchInput: "[data-search-input]",
    searchForm: "[data-search-form]",
    cartCount: "[data-cart-count]",
    cartContainer: "[data-cart-container]",
    cartSummary: "[data-cart-summary]",
    cartEmpty: "[data-cart-empty]",
    listingGrid: "[data-listing-grid]",
    listingCount: "[data-listing-count]",
    listingLoad: "[data-load-more]",
    filtersForm: "[data-filters-form]",
    productRoot: "[data-product-root]",
    relatedGrid: "[data-related-grid]",
    checkoutForm: "[data-checkout-form]",
    checkoutStatus: "[data-checkout-status]",
    toastRegion: "[data-toast]",
  },
};
