export const navItems = [
  { label: "Overview", route: "overview", status: "ready" },
  { label: "Buttons", route: "buttons", status: "ready" },
  { label: "Forms", route: "forms", status: "ready" },
  { label: "Inputs", route: "inputs", status: "ready" },
  { label: "Selects", route: "selects", status: "soon" },
  { label: "Toggles", route: "toggles", status: "soon" },
  { label: "Cards", route: "cards", status: "soon" },
  { label: "Badges", route: "badges", status: "soon" },
  { label: "Alerts", route: "alerts", status: "soon" },
  { label: "Tables", route: "tables", status: "soon" },
  { label: "Navigation", route: "navigation", status: "soon" },
  { label: "Modals", route: "modals", status: "soon" },
  { label: "Tooltips", route: "tooltips", status: "soon" },
  { label: "Dropdowns", route: "dropdowns", status: "soon" },
  { label: "Tabs", route: "tabs", status: "soon" },
  { label: "Pagination", route: "pagination", status: "soon" },
  { label: "Toasts", route: "toasts", status: "soon" },
  { label: "Loaders", route: "loaders", status: "soon" },
  { label: "Empty states", route: "empty-states", status: "soon" },
  { label: "Icons", route: "icons", status: "soon" },
  { label: "Accessibility", route: "accessibility", status: "soon" },
  { label: "Changelog", route: "changelog", status: "soon" },
  { label: "Download", route: "download", status: "ready" },
];
