// content/en.js
export const en = {
  common: {
    soon: "Soon",
    downloadCss: "Download CSS",
    toggleTheme: "Toggle theme",
  },
  overview: {
    title: "Overview",
    description: "Snapshot of the Core UI Components Pack status.",
    purposeTitle: "Purpose",
    purposeText: "Centralize UI component rules and layouts for fast product builds.",
    insideTitle: "What’s inside",
    insideBullets: ["Base layout patterns", "Component placeholders", "Downloadable CSS pack"],
    nextTitle: "Next up",
    nextText: "Finalize tokens, then lock in component-level styles.",
  },
  buttons: {
    title: "Buttons",
    description: "Button system packs and usage examples.",

    pack01Title: "Buttons Pack 01",
    pack01Description: "Primary button styles, sizes, states and mobile usage.",

    pack02Title: "Buttons Pack 02",
    pack02Description: "Alternate variants and label patterns (work in progress).",

    pack03Title: "Buttons Pack 03",
    pack03Description: "Progressive + destructive patterns (work in progress).",

    sectionButtonSize: "Button size",
    sectionButtonLabelStyle: "Button label style",
    sectionStates: "States",
    sectionMobileSizeExample: "Mobile size example",
    sectionIconButtons: "Icon buttons",
    sectionLoadingFeedback: "Loading & feedback",
    sectionVariants: "Variants",
    sectionLabelPatterns: "Label patterns",
    sectionSizes: "Sizes",
    sectionProgressiveActions: "Progressive actions",
    sectionDestructive: "Destructive",
    sectionMobile: "Mobile",

    labels: {
      small: "Small",
      medium: "Medium",
      large: "Large",
      button: "Button",
      create: "Create",
      download: "Download",
      apply: "Apply",
      delete: "Delete",
      disabled: "Disabled",
      mainCta: "Main CTA",
      add: "Add +",
      upload: "Upload ↑",
      onlyIcon: "Only icon",
      saving: "Saving…",
      success: "Success",
      retry: "Retry",
      primary: "Primary",
      outline: "Outline",
      ghost: "Ghost",
      save: "Save",
      export: "Export",
      share: "Share",
      confirm: "Confirm",
      remove: "Remove",
      continue: "Continue",
      loading: "Loading",
      next: "Next",
      finish: "Finish",
      archive: "Archive",
      start: "Start",
    },
  },
};
