// content/pl.js
export const pl = {
  common: {
    soon: "Wkrótce",
    downloadCss: "Pobierz CSS",
    toggleTheme: "Zmień motyw",
  },
  
  overview: {
    title: "Przegląd",
    description: "Szybki podgląd statusu paczki Core UI Components.",
    purposeTitle: "Cel",
    purposeText: "Ujednolicenie zasad komponentów i layoutów, aby szybciej budować produkty.",
    insideTitle: "Co zawiera",
    insideBullets: ["Bazowe wzorce layoutów", "Placeholdery komponentów", "Paczka CSS do pobrania"],
    nextTitle: "Następne kroki",
    nextText: "Dopięcie tokenów, potem domknięcie stylów na poziomie komponentów.",
  },

  buttons: {
    title: "Przyciski",
    description: "Paczki systemu przycisków i przykłady użycia.",

    pack01Title: "Buttons Pack 01",
    pack01Description: "Główne style przycisków, rozmiary, stany i użycie na mobile.",

    pack02Title: "Buttons Pack 02",
    pack02Description: "Alternatywne warianty i wzorce etykiet (w przygotowaniu).",

    pack03Title: "Buttons Pack 03",
    pack03Description: "Wzorce progresywne i destrukcyjne (w przygotowaniu).",

    sectionButtonSize: "Rozmiar przycisku",
    sectionButtonLabelStyle: "Styl etykiety",
    sectionStates: "Stany",
    sectionMobileSizeExample: "Przykład rozmiaru na mobile",
    sectionIconButtons: "Przyciski z ikoną",
    sectionLoadingFeedback: "Ładowanie i feedback",
    sectionVariants: "Warianty",
    sectionLabelPatterns: "Wzorce etykiet",
    sectionSizes: "Rozmiary",
    sectionProgressiveActions: "Akcje progresywne",
    sectionDestructive: "Destrukcyjne",
    sectionMobile: "Mobile",

    labels: {
      small: "Mały",
      medium: "Średni",
      large: "Duży",
      button: "Przycisk",
      create: "Utwórz",
      download: "Pobierz",
      apply: "Zastosuj",
      delete: "Usuń",
      disabled: "Wyłączony",
      mainCta: "Główne CTA",
      add: "Dodaj +",
      upload: "Wyślij ↑",
      onlyIcon: "Tylko ikona",
      saving: "Zapisywanie…",
      success: "Sukces",
      retry: "Ponów",
      primary: "Primary",
      outline: "Outline",
      ghost: "Ghost",
      save: "Zapisz",
      export: "Eksport",
      share: "Udostępnij",
      confirm: "Potwierdź",
      remove: "Usuń",
      continue: "Kontynuuj",
      loading: "Ładowanie",
      next: "Dalej",
      finish: "Zakończ",
      archive: "Archiwizuj",
      start: "Start",
    },
  },
};
